In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
class_lr=pd.read_csv('/content/drive/MyDrive/Python Datasets/Social_Network_Ads(1).csv')

In [4]:
class_lr.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
class_lr.shape

(400, 5)

In [ ]:
class_lr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [ ]:
class_lr.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

# Separate Dependent and independent Variables

In [5]:
X=class_lr.iloc[:,[1,2,3]].values
y=class_lr.iloc[:,4].values

In [ ]:
print(X)

[[1 19 19000]
 [1 35 20000]
 [0 26 43000]
 ...
 [0 50 20000]
 [1 36 33000]
 [0 49 36000]]


In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

# Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [9]:
print(X_train)

[[ 0.99288247 -1.1631724  -1.5849703 ]
 [ 0.99288247  2.17018137  0.93098672]
 [-1.00716855  0.0133054   1.22017719]
 [ 0.99288247  0.20938504  1.07558195]
 [-1.00716855  0.40546467 -0.48604654]
 [ 0.99288247 -0.28081405 -0.31253226]
 [ 0.99288247  0.99370357 -0.8330751 ]
 [-1.00716855  0.99370357  1.8563962 ]
 [-1.00716855  0.0133054   1.24909623]
 [ 0.99288247 -0.86905295  2.26126285]
 [-1.00716855 -1.1631724  -1.5849703 ]
 [ 0.99288247  2.17018137 -0.80415605]
 [ 0.99288247 -1.35925203 -1.46929411]
 [ 0.99288247  0.40546467  2.2901819 ]
 [-1.00716855  0.79762394  0.75747245]
 [ 0.99288247 -0.96709276 -0.31253226]
 [ 0.99288247  0.11134522  0.75747245]
 [ 0.99288247 -0.96709276  0.55503912]
 [ 0.99288247  0.30742485  0.06341534]
 [ 0.99288247  0.69958412 -1.26686079]
 [-1.00716855 -0.47689368 -0.0233418 ]
 [-1.00716855 -1.7514113   0.3526058 ]
 [ 0.99288247 -0.67297331  0.12125343]
 [ 0.99288247  0.40546467  0.29476771]
 [-1.00716855 -0.28081405  0.06341534]
 [-1.00716855 -0.47689368

In [10]:
from sklearn.linear_model import LogisticRegression
classifierLR=LogisticRegression()
classifierLR.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_predLR=classifierLR.predict(X_test)

In [16]:
y_predLR

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [13]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1])

In [18]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predLR)
print('Confusion Matrix: Logistic Regression')
print(cm)

Confusion Matrix: Logistic Regression
[[74  5]
 [ 8 33]]


In [19]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [24]:
print('Accuracy:%.2f'%(accuracy_score(y_test,y_predLR)*100))
print('Precision:%.3f'%(precision_score(y_test,y_predLR)))
print('Recall:%.3f'%(recall_score(y_test,y_predLR)))
print('F1 Score:%.3f'%(f1_score(y_test,y_predLR)))

Accuracy:89.17
Precision:0.868
Recall:0.805
F1 Score:0.835


# Implement Gaussian NB

In [25]:
from sklearn.naive_bayes import GaussianNB
classifierNB=GaussianNB()
classifierNB.fit(X_train,y_train)

GaussianNB()

In [26]:
y_predNB=classifierNB.predict(X_test)


In [27]:
cmNB=confusion_matrix(y_test,y_predNB)
print('Confusion Matrix: Gaussian NB')
print(cmNB)

Confusion Matrix: Gaussian NB
[[76  3]
 [ 8 33]]


In [29]:
print('*******************Accuracy************************')
print('Accuracy-LR:%.2f'%(accuracy_score(y_test,y_predLR)*100))
print('Accuracy-NB:%.2f'%(accuracy_score(y_test,y_predNB)*100))
print('******************Precision*************************')
print('Precision-LR:%.3f'%(precision_score(y_test,y_predLR)))
print('Precision-NB:%.3f'%(precision_score(y_test,y_predNB)))
print('*******************Recall***************************')
print('Recall-LR:%.3f'%(recall_score(y_test,y_predLR)))
print('Recall-NB:%.3f'%(recall_score(y_test,y_predNB)))
print('*****************F1 Score***************************')
print('F1 Score-LR:%.3f'%(f1_score(y_test,y_predLR)))
print('F1 Score-NB:%.3f'%(f1_score(y_test,y_predNB)))

*******************Accuracy************************
Accuracy-LR:89.17
Accuracy-NB:90.83
******************Precision*************************
Precision-LR:0.868
Precision-NB:0.917
*******************Recall***************************
Recall-LR:0.805
Recall-NB:0.805
*****************F1 Score***************************
F1 Score-LR:0.835
F1 Score-NB:0.857
